name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: yarn install

      - name: Check type
        run: yarn tsc

      - name: Run lint
        run: yarn lint
