name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.4.0
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache_node_modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Check type
        run: yarn tsc

      - name: Run lint
        run: yarn lint
